name: Badge Status

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-status:
    name: Test Status for Badges
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: '6.0'
    
    - name: Quick Build Test
      run: swift build
    
    - name: Quick Test Run
      run: swift test
    
    - name: MockLogBackend Test Count
      run: |
        TEST_COUNT=$(swift test --filter "MockLogBackend" 2>&1 | grep -c "passed" || echo "0")
        echo "MockLogBackend tests passed: $TEST_COUNT"
        if [ "$TEST_COUNT" -lt "10" ]; then
          echo "❌ MockLogBackend tests failing"
          exit 1
        else
          echo "✅ MockLogBackend tests passing"
        fi
    
    - name: Update Test Status
      run: |
        echo "All MockLogBackend tests are passing ✅"