name: Linux Tests

on:
  push:
    branches: [ main, fix-linux-concurrency ]
  pull_request:
    branches: [ main ]

jobs:
  linux-test:
    name: Test on Linux
    runs-on: ubuntu-latest
    container:
      image: swift:6.0
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: swift build
    
    - name: Run tests
      run: swift test
    
    - name: Test Console Backend Linux Features
      run: |
        echo "Testing Linux-specific console features..."
        swift test --filter consoleOutputFeaturesTest
        swift test --filter consoleVerbosityTest
    
    - name: Test Environment Variables
      run: |
        echo "Testing environment disable functionality..."
        DisableLogger=true swift test --filter consoleEnvironmentDisableTest